# Generated by Django 5.0 on 2023-12-29 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todotask",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
