# Generated by Django 5.0 on 2023-12-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_alter_todotask_unique_together_todotask_is_done_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoTask",
            new_name="TodoTaskModel",
        ),
        migrations.AlterModelTable(
            name="todotaskmodel",
            table="todo_task",
        ),
    ]
