# Generated by Django 5.0 on 2024-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0004_rename_todotask_todotaskmodel_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="todotaskmodel",
            name="is_done_idx",
        ),
        migrations.AlterUniqueTogether(
            name="todotaskmodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="todotaskmodel",
            name="user_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="todotaskmodel",
            unique_together={("user_id", "uuid")},
        ),
        migrations.AddIndex(
            model_name="todotaskmodel",
            index=models.Index(fields=["user_id", "is_done"], name="is_done_idx"),
        ),
        migrations.AddIndex(
            model_name="todotaskmodel",
            index=models.Index(fields=["user_id", "created_at"], name="created_at_idx"),
        ),
    ]
